### ISSUE TITLE
Mark these accounts as bots

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/pi-activitypub-server#2]
Since these accounts are all bots, imho they should be marked as bots (as @podnews@social.podnews.net is).

Marking as bots adds additional filter opportunities for clients, and ensures trending tags aren't spammed by automation.

Further reading: https://superuser.com/questions/1439448/what-is-the-effect-of-ticking-this-is-a-bot-account-in-mastodon

**Comment by daveajones** [comment]
Done.
