### ISSUE TITLE
New episodes don’t show up in Mastodon

### ISSUE THREAD

**Issue by frederik-elwert** [Podcastindex-org/pi-activitypub-server#8]
Unfortunately, I cannot explain why this fails behind the scenes, so I can only describe the phenomenon:

I subscribed to the podcast @5893302@ap.podcastindex.org from my Mastodon account (@felwert@fedihum.org). But although a new episode has been published, it does not show up on the Mastodon feed (at <https://fedihum.org/@5893302@ap.podcastindex.org>). The last (and only) episode shown here is Episode 5.

If I go to the AP page at <https://ap.podcastindex.org/podcasts?id=5893302>, I can navigate to the outbox at <https://ap.podcastindex.org/outbox?id=5893302&page=true>, and interestingly the new episode (episode 6) does show up there. I lack the background knowledge to understand why this doesn’t propagate to my instance.

**Comment by daveajones** [comment]
I fixed a bug with the bridge's handling of Mastodon authorized fetch yesterday.  See if this fixes the issue.  Also, if you create a toot that mentions @5893302@ap.podcastindex.org in it with the text "latest", it should send you the most recent episode.  Test that and report back.

**Comment by frederik-elwert** [comment]
Thanks! I tested the "latest" trick and that worked. The podcast has quite a low frequency, so I'll have to wait and see if the next episode also shows up normally.
